### ISSUE TITLE
create layout on figma

### ISSUE THREAD

**Issue by fbusche** [hyperloopiit/hoverpod#6]
*** display IS a touchscreen
- temp (each battery)
- speed arrow (velocity and direction)
- voltage (each battery)
- what's on and off (switch/button for that)
- bug testing console?? (for software team)
- error pop up page (if we have any failsafe)
- percent battery capacity (max and min vals. give voltage reading and percent until stop, not percent until 0. Should be able to E30 Samsung 21700. Figure out their cycles and what percent is accurate to that)
- should be able to turn on all the different parts (motors, etc.)

**Comment by ty-dwyer** [comment]
[gui V1.pdf](https://github.com/hyperloopiit/hoverpod/files/8201239/gui.V1.pdf)

**Comment by fbusche** [comment]
have to discuss during meeting if we can use mult screens or if that's going to be too much to sort through. Might have to limit the amount of data we receive.
